# Generated by Django 5.0.1 on 2024-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
